OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.get(CassandraKeyValueServiceImpl.java:565)
	at com.palantir.atlasdb.keyvalue.impl.AbstractKeyValueService.getLatestTimestamps(AbstractKeyValueService.java:141)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getLatestTimestamps(CassandraKeyValueServiceImpl.java:942)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getLatestTimestamps$18(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:394)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getLatestTimestamps(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getLatestTimestamps(ForwardingKeyValueService.java:121)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getLatestTimestamps(TracingKeyValueService.java:223)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getLatestTimestamps(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getLatestTimestamps(ValidatingQueryRewritingKeyValueService.java:173)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.detectWriteAlreadyCommittedInternal(SnapshotTransaction.java:1555)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfWriteAlreadyCommitted(SnapshotTransaction.java:1458)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfConflictOnCommit(SnapshotTransaction.java:1436)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commitWrites(SnapshotTransaction.java:1311)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1269)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1235)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.commit(ForwardingTransaction.java:129)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:104)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:91)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: com.palantir.common.exception.PalantirRuntimeException: com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.
	at com.palantir.common.base.Throwables.createPalantirRuntimeException(Throwables.java:116)
	at com.palantir.common.base.Throwables.createPalantirRuntimeException(Throwables.java:109)
	at com.palantir.common.base.Throwables.throwUncheckedException(Throwables.java:97)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2466)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.loadWithTs(CassandraKeyValueServiceImpl.java:606)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.get(CassandraKeyValueServiceImpl.java:551)
	... 35 more
Caused by: java.util.concurrent.ExecutionException: com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2457)
	... 37 more
Caused by: com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1216)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.access$300(CassandraKeyValueServiceImpl.java:156)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:660)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:638)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:126)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.remoting3.tracing.Tracers$TracingAwareCallable.call(Tracers.java:127)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.palantir.common.concurrent.ForwardingRunnableFuture.run(ForwardingRunnableFuture.java:55)
	at com.palantir.common.concurrent.PTExecutors$5.run(PTExecutors.java:486)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.] occurred while processing thread (Atlas loadWithTs 1 cells from default.todo on /127.0.0.2:9160 Atlas Cassandra KVS-32)
		... 17 more
Caused by: UnavailableException()
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14687)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14633)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result.read(Cassandra.java:14559)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_multiget_slice(Cassandra.java:741)
	at org.apache.cassandra.thrift.Cassandra$Client.multiget_slice(Cassandra.java:725)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$multigetInternal$13(CassandraKeyValueServiceImpl.java:1214)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:51)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:60)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1214)
	... 16 more
=============================================================================
OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2446)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.loadWithTs(CassandraKeyValueServiceImpl.java:606)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getRowsForSpecificColumns(CassandraKeyValueServiceImpl.java:520)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getRows(CassandraKeyValueServiceImpl.java:426)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getRows$23(ProfilingKeyValueService.java:255)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getRows(ProfilingKeyValueService.java:255)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getRows(ForwardingKeyValueService.java:101)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getRows(TracingKeyValueService.java:283)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getRows(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getRows(ValidatingQueryRewritingKeyValueService.java:181)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.getRows(SnapshotTransaction.java:357)
	at com.palantir.atlasdb.transaction.impl.SerializableTransaction.getRows(SerializableTransaction.java:144)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.getRows(ForwardingTransaction.java:55)
	at com.palantir.atlasdb.server.generated.TodoTable.getRows(TodoTable.java:499)
	at com.palantir.atlasdb.server.generated.TodoTable.getRows(TodoTable.java:494)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.lambda$runTxns$2(AtlasDbServiceServer.java:110)
	at com.palantir.atlasdb.transaction.api.LockAwareTransactionTasks$1.execute(LockAwareTransactionTasks.java:32)
	at com.palantir.atlasdb.transaction.api.LockAwareTransactionTasks.lambda$asLockUnaware$0(LockAwareTransactionTasks.java:49)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:102)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:107)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1216)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.access$300(CassandraKeyValueServiceImpl.java:156)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:660)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:638)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:126)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2444)
	... 35 more
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.] occurred while processing thread (Atlas loadWithTs 2 cells from default.todo on /127.0.0.3:9160 main)
		... 46 more
Caused by: UnavailableException()
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14687)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14633)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result.read(Cassandra.java:14559)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_multiget_slice(Cassandra.java:741)
	at org.apache.cassandra.thrift.Cassandra$Client.multiget_slice(Cassandra.java:725)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$multigetInternal$13(CassandraKeyValueServiceImpl.java:1214)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:51)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:60)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1214)
	... 45 more
=============================================================================
OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2446)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.loadWithTs(CassandraKeyValueServiceImpl.java:606)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.get(CassandraKeyValueServiceImpl.java:551)
	at com.palantir.atlasdb.keyvalue.impl.AbstractKeyValueService.getLatestTimestamps(AbstractKeyValueService.java:141)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getLatestTimestamps(CassandraKeyValueServiceImpl.java:942)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getLatestTimestamps$18(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:394)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getLatestTimestamps(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getLatestTimestamps(ForwardingKeyValueService.java:121)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getLatestTimestamps(TracingKeyValueService.java:223)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getLatestTimestamps(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getLatestTimestamps(ValidatingQueryRewritingKeyValueService.java:173)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.detectWriteAlreadyCommittedInternal(SnapshotTransaction.java:1555)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfWriteAlreadyCommitted(SnapshotTransaction.java:1458)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfConflictOnCommit(SnapshotTransaction.java:1436)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commitWrites(SnapshotTransaction.java:1311)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1269)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1235)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.commit(ForwardingTransaction.java:129)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:104)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:122)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1216)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.access$300(CassandraKeyValueServiceImpl.java:156)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:660)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:638)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:126)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2444)
	... 37 more
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.] occurred while processing thread (Atlas loadWithTs 1 cells from default.todo on /127.0.0.3:9160 main)
		... 48 more
Caused by: UnavailableException()
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14687)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14633)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result.read(Cassandra.java:14559)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_multiget_slice(Cassandra.java:741)
	at org.apache.cassandra.thrift.Cassandra$Client.multiget_slice(Cassandra.java:725)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$multigetInternal$13(CassandraKeyValueServiceImpl.java:1214)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:51)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:60)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1214)
	... 47 more
=============================================================================
OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2446)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.loadWithTs(CassandraKeyValueServiceImpl.java:606)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.get(CassandraKeyValueServiceImpl.java:551)
	at com.palantir.atlasdb.keyvalue.impl.AbstractKeyValueService.getLatestTimestamps(AbstractKeyValueService.java:141)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getLatestTimestamps(CassandraKeyValueServiceImpl.java:942)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getLatestTimestamps$18(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:394)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getLatestTimestamps(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getLatestTimestamps(ForwardingKeyValueService.java:121)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getLatestTimestamps(TracingKeyValueService.java:223)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getLatestTimestamps(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getLatestTimestamps(ValidatingQueryRewritingKeyValueService.java:173)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.detectWriteAlreadyCommittedInternal(SnapshotTransaction.java:1555)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfWriteAlreadyCommitted(SnapshotTransaction.java:1458)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfConflictOnCommit(SnapshotTransaction.java:1436)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commitWrites(SnapshotTransaction.java:1311)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1269)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1235)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.commit(ForwardingTransaction.java:129)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:104)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:91)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1216)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.access$300(CassandraKeyValueServiceImpl.java:156)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:660)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:638)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:126)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2444)
	... 37 more
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.] occurred while processing thread (Atlas loadWithTs 2 cells from default.todo on /127.0.0.3:9160 main)
		... 48 more
Caused by: UnavailableException()
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14687)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14633)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result.read(Cassandra.java:14559)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_multiget_slice(Cassandra.java:741)
	at org.apache.cassandra.thrift.Cassandra$Client.multiget_slice(Cassandra.java:725)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$multigetInternal$13(CassandraKeyValueServiceImpl.java:1214)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:51)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:60)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1214)
	... 47 more
=============================================================================
OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2446)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.loadWithTs(CassandraKeyValueServiceImpl.java:606)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getRowsForSpecificColumns(CassandraKeyValueServiceImpl.java:520)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getRows(CassandraKeyValueServiceImpl.java:426)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getRows$23(ProfilingKeyValueService.java:255)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getRows(ProfilingKeyValueService.java:255)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getRows(ForwardingKeyValueService.java:101)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getRows(TracingKeyValueService.java:283)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getRows(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getRows(ValidatingQueryRewritingKeyValueService.java:181)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.getRows(SnapshotTransaction.java:357)
	at com.palantir.atlasdb.transaction.impl.SerializableTransaction.getRows(SerializableTransaction.java:144)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.getRows(ForwardingTransaction.java:55)
	at com.palantir.atlasdb.server.generated.TodoTable.getRows(TodoTable.java:499)
	at com.palantir.atlasdb.server.generated.TodoTable.getRows(TodoTable.java:494)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.lambda$runTxns$2(AtlasDbServiceServer.java:110)
	at com.palantir.atlasdb.transaction.api.LockAwareTransactionTasks$1.execute(LockAwareTransactionTasks.java:32)
	at com.palantir.atlasdb.transaction.api.LockAwareTransactionTasks.lambda$asLockUnaware$0(LockAwareTransactionTasks.java:49)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:102)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:107)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1216)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.access$300(CassandraKeyValueServiceImpl.java:156)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:660)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:638)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:126)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2444)
	... 35 more
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.] occurred while processing thread (Atlas loadWithTs 2 cells from default.todo on /127.0.0.3:9160 main)
		... 46 more
Caused by: UnavailableException()
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14687)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14633)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result.read(Cassandra.java:14559)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_multiget_slice(Cassandra.java:741)
	at org.apache.cassandra.thrift.Cassandra$Client.multiget_slice(Cassandra.java:725)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$multigetInternal$13(CassandraKeyValueServiceImpl.java:1214)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:51)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:60)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1214)
	... 45 more
=============================================================================
OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2446)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.loadWithTs(CassandraKeyValueServiceImpl.java:606)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.get(CassandraKeyValueServiceImpl.java:551)
	at com.palantir.atlasdb.keyvalue.impl.AbstractKeyValueService.getLatestTimestamps(AbstractKeyValueService.java:141)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getLatestTimestamps(CassandraKeyValueServiceImpl.java:942)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getLatestTimestamps$18(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:394)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getLatestTimestamps(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getLatestTimestamps(ForwardingKeyValueService.java:121)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getLatestTimestamps(TracingKeyValueService.java:223)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getLatestTimestamps(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getLatestTimestamps(ValidatingQueryRewritingKeyValueService.java:173)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.detectWriteAlreadyCommittedInternal(SnapshotTransaction.java:1555)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfWriteAlreadyCommitted(SnapshotTransaction.java:1458)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfConflictOnCommit(SnapshotTransaction.java:1436)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commitWrites(SnapshotTransaction.java:1311)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1269)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1235)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.commit(ForwardingTransaction.java:129)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:104)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:122)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1216)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.access$300(CassandraKeyValueServiceImpl.java:156)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:660)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:638)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:126)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2444)
	... 37 more
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.] occurred while processing thread (Atlas loadWithTs 1 cells from default.todo on /127.0.0.3:9160 main)
		... 48 more
Caused by: UnavailableException()
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14687)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14633)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result.read(Cassandra.java:14559)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_multiget_slice(Cassandra.java:741)
	at org.apache.cassandra.thrift.Cassandra$Client.multiget_slice(Cassandra.java:725)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$multigetInternal$13(CassandraKeyValueServiceImpl.java:1214)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:51)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:60)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1214)
	... 47 more
=============================================================================
OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2446)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.loadWithTs(CassandraKeyValueServiceImpl.java:606)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.get(CassandraKeyValueServiceImpl.java:551)
	at com.palantir.atlasdb.keyvalue.impl.AbstractKeyValueService.getLatestTimestamps(AbstractKeyValueService.java:141)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getLatestTimestamps(CassandraKeyValueServiceImpl.java:942)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getLatestTimestamps$18(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:394)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getLatestTimestamps(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getLatestTimestamps(ForwardingKeyValueService.java:121)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getLatestTimestamps(TracingKeyValueService.java:223)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getLatestTimestamps(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getLatestTimestamps(ValidatingQueryRewritingKeyValueService.java:173)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.detectWriteAlreadyCommittedInternal(SnapshotTransaction.java:1555)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfWriteAlreadyCommitted(SnapshotTransaction.java:1458)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfConflictOnCommit(SnapshotTransaction.java:1436)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commitWrites(SnapshotTransaction.java:1311)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1269)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1235)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.commit(ForwardingTransaction.java:129)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:104)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:91)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: org.apache.thrift.transport.TTransportException
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129)
	at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_multiget_slice(Cassandra.java:741)
	at org.apache.cassandra.thrift.Cassandra$Client.multiget_slice(Cassandra.java:725)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$multigetInternal$13(CassandraKeyValueServiceImpl.java:1214)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:51)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:60)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1214)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.access$300(CassandraKeyValueServiceImpl.java:156)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:660)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:638)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:126)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2444)
	... 37 more
	Suppressed: Exception [org.apache.thrift.transport.TTransportException] occurred while processing thread (Atlas loadWithTs 2 cells from default.todo on /127.0.0.3:9160 main)
		... 62 more
=============================================================================
OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2446)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.loadWithTs(CassandraKeyValueServiceImpl.java:606)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getRowsForSpecificColumns(CassandraKeyValueServiceImpl.java:520)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getRows(CassandraKeyValueServiceImpl.java:426)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getRows$23(ProfilingKeyValueService.java:255)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getRows(ProfilingKeyValueService.java:255)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getRows(ForwardingKeyValueService.java:101)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getRows(TracingKeyValueService.java:283)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getRows(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getRows(ValidatingQueryRewritingKeyValueService.java:181)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.getRows(SnapshotTransaction.java:357)
	at com.palantir.atlasdb.transaction.impl.SerializableTransaction.getRows(SerializableTransaction.java:144)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.getRows(ForwardingTransaction.java:55)
	at com.palantir.atlasdb.server.generated.TodoTable.getRows(TodoTable.java:499)
	at com.palantir.atlasdb.server.generated.TodoTable.getRows(TodoTable.java:494)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.lambda$runTxns$2(AtlasDbServiceServer.java:110)
	at com.palantir.atlasdb.transaction.api.LockAwareTransactionTasks$1.execute(LockAwareTransactionTasks.java:32)
	at com.palantir.atlasdb.transaction.api.LockAwareTransactionTasks.lambda$asLockUnaware$0(LockAwareTransactionTasks.java:49)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:102)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:107)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.1:9160/atlasete2
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:85)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:53)
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:458)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:125)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2444)
	... 35 more
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.1:9160/atlasete2] occurred while processing thread (Atlas loadWithTs 2 cells from default.todo on /127.0.0.3:9160 main)
		... 48 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
	at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClientInternal(CassandraClientFactory.java:110)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClient(CassandraClientFactory.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:79)
	... 47 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
	... 50 more
=============================================================================
OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2446)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.loadWithTs(CassandraKeyValueServiceImpl.java:606)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.get(CassandraKeyValueServiceImpl.java:551)
	at com.palantir.atlasdb.keyvalue.impl.AbstractKeyValueService.getLatestTimestamps(AbstractKeyValueService.java:141)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getLatestTimestamps(CassandraKeyValueServiceImpl.java:942)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getLatestTimestamps$18(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:394)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getLatestTimestamps(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getLatestTimestamps(ForwardingKeyValueService.java:121)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getLatestTimestamps(TracingKeyValueService.java:223)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getLatestTimestamps(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getLatestTimestamps(ValidatingQueryRewritingKeyValueService.java:173)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.detectWriteAlreadyCommittedInternal(SnapshotTransaction.java:1555)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfWriteAlreadyCommitted(SnapshotTransaction.java:1458)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfConflictOnCommit(SnapshotTransaction.java:1436)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commitWrites(SnapshotTransaction.java:1311)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1269)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1235)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.commit(ForwardingTransaction.java:129)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:104)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:122)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.2:9160/atlasete2
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:85)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:53)
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:458)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:125)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2444)
	... 37 more
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.2:9160/atlasete2] occurred while processing thread (Atlas loadWithTs 1 cells from default.todo on /127.0.0.2:9160 main)
		... 50 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
	at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClientInternal(CassandraClientFactory.java:110)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClient(CassandraClientFactory.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:79)
	... 49 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
	... 52 more
=============================================================================
OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.get(CassandraKeyValueServiceImpl.java:565)
	at com.palantir.atlasdb.keyvalue.impl.AbstractKeyValueService.getLatestTimestamps(AbstractKeyValueService.java:141)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getLatestTimestamps(CassandraKeyValueServiceImpl.java:942)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getLatestTimestamps$18(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:394)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getLatestTimestamps(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getLatestTimestamps(ForwardingKeyValueService.java:121)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getLatestTimestamps(TracingKeyValueService.java:223)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getLatestTimestamps(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getLatestTimestamps(ValidatingQueryRewritingKeyValueService.java:173)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.detectWriteAlreadyCommittedInternal(SnapshotTransaction.java:1555)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfWriteAlreadyCommitted(SnapshotTransaction.java:1458)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfConflictOnCommit(SnapshotTransaction.java:1436)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commitWrites(SnapshotTransaction.java:1311)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1269)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1235)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.commit(ForwardingTransaction.java:129)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:104)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:91)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.2:9160/atlasete2
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:85)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:53)
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:458)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:125)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.remoting3.tracing.Tracers$TracingAwareCallable.call(Tracers.java:127)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.palantir.common.concurrent.ForwardingRunnableFuture.run(ForwardingRunnableFuture.java:55)
	at com.palantir.common.concurrent.PTExecutors$5.run(PTExecutors.java:486)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.2:9160/atlasete2] occurred while processing thread (Atlas loadWithTs 1 cells from default.todo on /127.0.0.1:9160 Atlas Cassandra KVS-60)
		... 19 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
	at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClientInternal(CassandraClientFactory.java:110)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClient(CassandraClientFactory.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:79)
	... 18 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
	... 21 more
=============================================================================
OHH NO! looks like the tm throws something.Failed to construct client for /127.0.0.3:9160/atlasete2
com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.3:9160/atlasete2
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:85)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:53)
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:458)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:125)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.remoting3.tracing.Tracers$TracingAwareCallable.call(Tracers.java:127)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.palantir.common.concurrent.ForwardingRunnableFuture.run(ForwardingRunnableFuture.java:55)
	at com.palantir.common.concurrent.PTExecutors$5.run(PTExecutors.java:486)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.3:9160/atlasete2] occurred while processing thread (Atlas loadWithTs 1 cells from default.todo on /127.0.0.1:9160 Atlas Cassandra KVS-62)
		... 19 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
	at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClientInternal(CassandraClientFactory.java:110)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClient(CassandraClientFactory.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:79)
	... 18 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
	... 21 more
=============================================================================
OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2446)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.loadWithTs(CassandraKeyValueServiceImpl.java:606)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.get(CassandraKeyValueServiceImpl.java:551)
	at com.palantir.atlasdb.keyvalue.impl.AbstractKeyValueService.getLatestTimestamps(AbstractKeyValueService.java:141)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getLatestTimestamps(CassandraKeyValueServiceImpl.java:942)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getLatestTimestamps$18(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:394)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getLatestTimestamps(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getLatestTimestamps(ForwardingKeyValueService.java:121)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getLatestTimestamps(TracingKeyValueService.java:223)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getLatestTimestamps(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getLatestTimestamps(ValidatingQueryRewritingKeyValueService.java:173)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.detectWriteAlreadyCommittedInternal(SnapshotTransaction.java:1555)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfWriteAlreadyCommitted(SnapshotTransaction.java:1458)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfConflictOnCommit(SnapshotTransaction.java:1436)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commitWrites(SnapshotTransaction.java:1311)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1269)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1235)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.commit(ForwardingTransaction.java:129)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:104)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:122)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.2:9160/atlasete2
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:85)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:53)
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:458)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:125)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2444)
	... 37 more
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.2:9160/atlasete2] occurred while processing thread (Atlas loadWithTs 1 cells from default.todo on /127.0.0.1:9160 main)
		... 50 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
	at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClientInternal(CassandraClientFactory.java:110)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClient(CassandraClientFactory.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:79)
	... 49 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
	... 52 more
=============================================================================
OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.get(CassandraKeyValueServiceImpl.java:565)
	at com.palantir.atlasdb.keyvalue.impl.AbstractKeyValueService.getLatestTimestamps(AbstractKeyValueService.java:141)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getLatestTimestamps(CassandraKeyValueServiceImpl.java:942)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getLatestTimestamps$18(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:394)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getLatestTimestamps(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getLatestTimestamps(ForwardingKeyValueService.java:121)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getLatestTimestamps(TracingKeyValueService.java:223)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getLatestTimestamps(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getLatestTimestamps(ValidatingQueryRewritingKeyValueService.java:173)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.detectWriteAlreadyCommittedInternal(SnapshotTransaction.java:1555)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfWriteAlreadyCommitted(SnapshotTransaction.java:1458)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfConflictOnCommit(SnapshotTransaction.java:1436)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commitWrites(SnapshotTransaction.java:1311)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1269)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1235)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.commit(ForwardingTransaction.java:129)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:104)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:91)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.3:9160/atlasete2
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:85)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:53)
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:458)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:125)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.remoting3.tracing.Tracers$TracingAwareCallable.call(Tracers.java:127)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.palantir.common.concurrent.ForwardingRunnableFuture.run(ForwardingRunnableFuture.java:55)
	at com.palantir.common.concurrent.PTExecutors$5.run(PTExecutors.java:486)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.3:9160/atlasete2] occurred while processing thread (Atlas loadWithTs 1 cells from default.todo on /127.0.0.2:9160 Atlas Cassandra KVS-64)
		... 19 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
	at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClientInternal(CassandraClientFactory.java:110)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClient(CassandraClientFactory.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:79)
	... 18 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
	... 21 more
=============================================================================
OHH NO! looks like the tm throws something.Failed to construct client for /127.0.0.3:9160/atlasete2
com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.3:9160/atlasete2
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:85)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:53)
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:458)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:125)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.remoting3.tracing.Tracers$TracingAwareCallable.call(Tracers.java:127)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.palantir.common.concurrent.ForwardingRunnableFuture.run(ForwardingRunnableFuture.java:55)
	at com.palantir.common.concurrent.PTExecutors$5.run(PTExecutors.java:486)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.3:9160/atlasete2] occurred while processing thread (Atlas loadWithTs 1 cells from default.todo on /127.0.0.1:9160 Atlas Cassandra KVS-66)
		... 19 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
	at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClientInternal(CassandraClientFactory.java:110)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClient(CassandraClientFactory.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:79)
	... 18 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
	... 21 more
=============================================================================
OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2446)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.loadWithTs(CassandraKeyValueServiceImpl.java:606)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.get(CassandraKeyValueServiceImpl.java:551)
	at com.palantir.atlasdb.keyvalue.impl.AbstractKeyValueService.getLatestTimestamps(AbstractKeyValueService.java:141)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getLatestTimestamps(CassandraKeyValueServiceImpl.java:942)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getLatestTimestamps$18(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:394)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getLatestTimestamps(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getLatestTimestamps(ForwardingKeyValueService.java:121)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getLatestTimestamps(TracingKeyValueService.java:223)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getLatestTimestamps(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getLatestTimestamps(ValidatingQueryRewritingKeyValueService.java:173)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.detectWriteAlreadyCommittedInternal(SnapshotTransaction.java:1555)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfWriteAlreadyCommitted(SnapshotTransaction.java:1458)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfConflictOnCommit(SnapshotTransaction.java:1436)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commitWrites(SnapshotTransaction.java:1311)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1269)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1235)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.commit(ForwardingTransaction.java:129)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:104)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:122)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.3:9160/atlasete2
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:85)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:53)
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:458)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:125)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2444)
	... 37 more
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.3:9160/atlasete2] occurred while processing thread (Atlas loadWithTs 1 cells from default.todo on /127.0.0.1:9160 main)
		... 50 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
	at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClientInternal(CassandraClientFactory.java:110)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClient(CassandraClientFactory.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:79)
	... 49 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
	... 52 more
=============================================================================
OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2446)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.loadWithTs(CassandraKeyValueServiceImpl.java:606)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.get(CassandraKeyValueServiceImpl.java:551)
	at com.palantir.atlasdb.keyvalue.impl.AbstractKeyValueService.getLatestTimestamps(AbstractKeyValueService.java:141)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getLatestTimestamps(CassandraKeyValueServiceImpl.java:942)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getLatestTimestamps$18(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:394)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getLatestTimestamps(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getLatestTimestamps(ForwardingKeyValueService.java:121)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getLatestTimestamps(TracingKeyValueService.java:223)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getLatestTimestamps(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getLatestTimestamps(ValidatingQueryRewritingKeyValueService.java:173)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.detectWriteAlreadyCommittedInternal(SnapshotTransaction.java:1555)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfWriteAlreadyCommitted(SnapshotTransaction.java:1458)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfConflictOnCommit(SnapshotTransaction.java:1436)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commitWrites(SnapshotTransaction.java:1311)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1269)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1235)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.commit(ForwardingTransaction.java:129)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:104)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:91)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.3:9160/atlasete2
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:85)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:53)
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:458)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:125)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2444)
	... 37 more
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory$ClientCreationFailedException: Failed to construct client for /127.0.0.3:9160/atlasete2] occurred while processing thread (Atlas loadWithTs 2 cells from default.todo on /127.0.0.3:9160 main)
		... 50 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
	at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClientInternal(CassandraClientFactory.java:110)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClient(CassandraClientFactory.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create(CassandraClientFactory.java:79)
	... 49 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
	... 52 more
=============================================================================
OHH NO! looks like the tm throws something.com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.
com.palantir.common.exception.PalantirRuntimeException: com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.
	at com.palantir.common.base.Throwables.createPalantirRuntimeException(Throwables.java:116)
	at com.palantir.common.base.Throwables.createPalantirRuntimeException(Throwables.java:109)
	at com.palantir.common.base.Throwables.throwUncheckedException(Throwables.java:97)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2466)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.loadWithTs(CassandraKeyValueServiceImpl.java:606)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getRowsForSpecificColumns(CassandraKeyValueServiceImpl.java:520)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getRows(CassandraKeyValueServiceImpl.java:426)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getRows$23(ProfilingKeyValueService.java:255)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getRows(ProfilingKeyValueService.java:255)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getRows(ForwardingKeyValueService.java:101)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getRows(TracingKeyValueService.java:283)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getRows(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getRows(ValidatingQueryRewritingKeyValueService.java:181)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.getRows(SnapshotTransaction.java:357)
	at com.palantir.atlasdb.transaction.impl.SerializableTransaction.getRows(SerializableTransaction.java:144)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.getRows(ForwardingTransaction.java:55)
	at com.palantir.atlasdb.server.generated.TodoTable.getRows(TodoTable.java:499)
	at com.palantir.atlasdb.server.generated.TodoTable.getRows(TodoTable.java:494)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.lambda$runTxns$2(AtlasDbServiceServer.java:110)
	at com.palantir.atlasdb.transaction.api.LockAwareTransactionTasks$1.execute(LockAwareTransactionTasks.java:32)
	at com.palantir.atlasdb.transaction.api.LockAwareTransactionTasks.lambda$asLockUnaware$0(LockAwareTransactionTasks.java:49)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:102)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:107)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: java.util.concurrent.ExecutionException: com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2457)
	... 35 more
Caused by: com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1216)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.access$300(CassandraKeyValueServiceImpl.java:156)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:660)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:638)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:126)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.remoting3.tracing.Tracers$TracingAwareCallable.call(Tracers.java:127)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.palantir.common.concurrent.ForwardingRunnableFuture.run(ForwardingRunnableFuture.java:55)
	at com.palantir.common.concurrent.PTExecutors$5.run(PTExecutors.java:486)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.] occurred while processing thread (Atlas loadWithTs 1 cells from default.todo on /127.0.0.1:9160 Atlas Cassandra KVS-68)
		... 17 more
Caused by: UnavailableException()
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14687)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14633)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result.read(Cassandra.java:14559)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_multiget_slice(Cassandra.java:741)
	at org.apache.cassandra.thrift.Cassandra$Client.multiget_slice(Cassandra.java:725)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$multigetInternal$13(CassandraKeyValueServiceImpl.java:1214)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:51)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:60)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1214)
	... 16 more
=============================================================================
OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2446)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.loadWithTs(CassandraKeyValueServiceImpl.java:606)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.get(CassandraKeyValueServiceImpl.java:551)
	at com.palantir.atlasdb.keyvalue.impl.AbstractKeyValueService.getLatestTimestamps(AbstractKeyValueService.java:141)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getLatestTimestamps(CassandraKeyValueServiceImpl.java:942)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getLatestTimestamps$18(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:394)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getLatestTimestamps(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getLatestTimestamps(ForwardingKeyValueService.java:121)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getLatestTimestamps(TracingKeyValueService.java:223)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getLatestTimestamps(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getLatestTimestamps(ValidatingQueryRewritingKeyValueService.java:173)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.detectWriteAlreadyCommittedInternal(SnapshotTransaction.java:1555)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfWriteAlreadyCommitted(SnapshotTransaction.java:1458)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfConflictOnCommit(SnapshotTransaction.java:1436)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commitWrites(SnapshotTransaction.java:1311)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1269)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1235)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.commit(ForwardingTransaction.java:129)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:104)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:122)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1216)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.access$300(CassandraKeyValueServiceImpl.java:156)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:660)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:638)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:126)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2444)
	... 37 more
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.] occurred while processing thread (Atlas loadWithTs 1 cells from default.todo on /127.0.0.1:9160 main)
		... 48 more
Caused by: UnavailableException()
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14687)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14633)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result.read(Cassandra.java:14559)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_multiget_slice(Cassandra.java:741)
	at org.apache.cassandra.thrift.Cassandra$Client.multiget_slice(Cassandra.java:725)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$multigetInternal$13(CassandraKeyValueServiceImpl.java:1214)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:51)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:60)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1214)
	... 47 more
=============================================================================
OHH NO! looks like the tm throws something.The KVS or Timelock threw an exception.
com.palantir.common.exception.AtlasDbDependencyException: The KVS or Timelock threw an exception.
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:105)
	at com.palantir.common.base.Throwables.unwrapAndThrowDependencyUnavailableException(Throwables.java:91)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2446)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.loadWithTs(CassandraKeyValueServiceImpl.java:606)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.get(CassandraKeyValueServiceImpl.java:551)
	at com.palantir.atlasdb.keyvalue.impl.AbstractKeyValueService.getLatestTimestamps(AbstractKeyValueService.java:141)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.getLatestTimestamps(CassandraKeyValueServiceImpl.java:942)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$getLatestTimestamps$18(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:113)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:394)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.getLatestTimestamps(ProfilingKeyValueService.java:215)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getLatestTimestamps(ForwardingKeyValueService.java:121)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.getLatestTimestamps(TracingKeyValueService.java:223)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:138)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:115)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:95)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy42.getLatestTimestamps(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.getLatestTimestamps(ValidatingQueryRewritingKeyValueService.java:173)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.detectWriteAlreadyCommittedInternal(SnapshotTransaction.java:1555)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfWriteAlreadyCommitted(SnapshotTransaction.java:1458)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.throwIfConflictOnCommit(SnapshotTransaction.java:1436)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commitWrites(SnapshotTransaction.java:1311)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1269)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.commit(SnapshotTransaction.java:1235)
	at com.palantir.atlasdb.transaction.impl.ForwardingTransaction.commit(ForwardingTransaction.java:129)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:104)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:128)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:36)
	at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123)
	at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55)
	at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:129)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.runTxns(AtlasDbServiceServer.java:91)
	at com.palantir.atlasdb.server.AtlasDbServiceServer.main(AtlasDbServiceServer.java:57)
Caused by: com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1216)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.access$300(CassandraKeyValueServiceImpl.java:156)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:660)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$2.apply(CassandraKeyValueServiceImpl.java:638)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:126)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:102)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:649)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:601)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$getLoadWithTsTasksForSingleHost$6(CassandraKeyValueServiceImpl.java:637)
	at com.palantir.atlasdb.util.AnnotatedCallable.call(AnnotatedCallable.java:54)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.runAllTasksCancelOnFailure(CassandraKeyValueServiceImpl.java:2444)
	... 37 more
	Suppressed: RuntimeException [com.palantir.atlasdb.keyvalue.api.InsufficientConsistencyException: This get operation requires LOCAL_QUORUM Cassandra nodes to be up and available.] occurred while processing thread (Atlas loadWithTs 2 cells from default.todo on /127.0.0.1:9160 main)
		... 48 more
Caused by: UnavailableException()
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14687)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14633)
	at org.apache.cassandra.thrift.Cassandra$multiget_slice_result.read(Cassandra.java:14559)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_multiget_slice(Cassandra.java:741)
	at org.apache.cassandra.thrift.Cassandra$Client.multiget_slice(Cassandra.java:725)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.lambda$multigetInternal$13(CassandraKeyValueServiceImpl.java:1214)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:51)
	at com.palantir.atlasdb.keyvalue.cassandra.TracingQueryRunner.run(TracingQueryRunner.java:60)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.multigetInternal(CassandraKeyValueServiceImpl.java:1214)
	... 47 more
=============================================================================
